name: Bug report
description: Report a bug or regression
labels: [bug]
body:
  - type: textarea
    attributes:
      label: What happened?
      description: Describe the issue and expected behavior
    validations:
      required: true
  - type: input
    attributes:
      label: Version/commit
      placeholder: e.g., 0.1.0 or commit hash
  - type: textarea
    attributes:
      label: Steps to reproduce
      placeholder: |
        1. Command you ran
        2. Output/logs
    validations:
      required: true
  - type: textarea
    attributes:
      label: Environment
      placeholder: OS, Python version
  - type: textarea
    attributes:
      label: Logs
      placeholder: Paste relevant logs/traceback
