name: Feature request
description: Suggest an idea or enhancement
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Problem
      description: What problem would this solve?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Proposal
      description: What do you want to see added/changed?
    validations:
      required: true
  - type: textarea
    attributes:
      label: Alternatives
      description: Any alternative solutions?
  - type: textarea
    attributes:
      label: Additional context
      description: Links, prior art, notes
